#!/usr/bin/env node
// Upload videos in public/videos/ to Vercel Blob and rewrite src/lib/videos.ts
// with the resulting public URLs.
//
// Usage:
//   1. npm i -g vercel
//   2. vercel link
//   3. vercel env pull .env.local        # pulls BLOB_READ_WRITE_TOKEN
//   4. node --env-file=.env.local scripts/upload-videos.mjs
//
// After it runs, commit the updated src/lib/videos.ts and (optionally)
// delete public/videos/*.mp4 from the repo to shed ~380 MB.

import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { put } from "@vercel/blob";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const mapping = {
  pitch: "public/videos/pitch.mp4",
  testimonial1: "public/videos/testimonial_1.mp4",
  testimonial2: "public/videos/testimonial_2.mp4",
  testimonial3: "public/videos/testimonial_3.mp4",
  testimonial4: "public/videos/testimonial_4.mp4",
  testimonial5: "public/videos/testimonial_5.mp4",
};

if (!process.env.BLOB_READ_WRITE_TOKEN) {
  console.error(
    "Missing BLOB_READ_WRITE_TOKEN. Run `vercel env pull .env.local`, then\n" +
      "`node --env-file=.env.local scripts/upload-videos.mjs`."
  );
  process.exit(1);
}

const results = {};
for (const [key, relPath] of Object.entries(mapping)) {
  const absPath = resolve(repoRoot, relPath);
  const data = await readFile(absPath);
  const blobName = `videos/${relPath.split("/").pop()}`;
  console.log(`Uploading ${relPath} (${(data.length / 1024 / 1024).toFixed(1)} MB)…`);
  const blob = await put(blobName, data, {
    access: "public",
    addRandomSuffix: false,
    allowOverwrite: true,
    contentType: "video/mp4",
  });
  results[key] = blob.url;
  console.log(`  → ${blob.url}`);
}

const configPath = resolve(repoRoot, "src/lib/videos.ts");
const newConfig = `// Centralized video URL config.
// These URLs point to Vercel Blob — generated by scripts/upload-videos.mjs.
export const videos = {
${Object.entries(results)
  .map(([k, v]) => `  ${k}: "${v}",`)
  .join("\n")}
} as const;
`;
await writeFile(configPath, newConfig);
console.log(`\n✅ Wrote ${configPath}`);
console.log(
  "Next: commit src/lib/videos.ts. You can also `git rm` public/videos/*.mp4\n" +
    "since the page no longer references them."
);
